version: '3'
services: 
  db:
    container_name: bdTiendaVaper
    image: mariadb
    environment:
      MARIADB_USER: TiendaVaper
      MARIADB_PASSWORD: pswTiendaVaper
      MARIADB_DATABASE: TiendaVaper
      MARIADB_ROOT_PASSWORD: 1234
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3308:3306"